# Generated by Django 2.2.6 on 2020-09-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0015_auto_20200923_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
                ('book', models.ManyToManyField(to='p_library.Book')),
            ],
        ),
    ]
