# Generated by Django 2.2.6 on 2020-09-29 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0016_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='book',
        ),
        migrations.AddField(
            model_name='friend',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='p_library.Book'),
        ),
    ]
