# Generated by Django 2.2.6 on 2020-09-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0017_auto_20200929_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='book',
        ),
        migrations.AddField(
            model_name='friend',
            name='book',
            field=models.ManyToManyField(related_name='book', to='p_library.Book'),
        ),
    ]
