# Generated by Django 2.2.6 on 2020-10-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0018_auto_20200929_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='books_image/%Y/%m/%d'),
        ),
    ]
